### PR TITLE
mirage-runtime: require either dune >= 3.22 or lwt < 6

### PR DESCRIPTION
**Pull request by hannesm**
see https://github.com/ocaml/dune/issues/13299

### CODE REVIEW

**Comment by palainp** [comment]
Dear @hannesm , thank you for your PR, it seems Ocaml 4.14 is fine with it, but Ocaml 5.[34] is not happy.
Locally, with mirage and mirage-runtime pinned to your PR, I have the same error with dune 3.22 and Ocaml 5.3 as with CI's :
```bash
$ dune --version
3.22.0
$ mirage clean && rm -rf duniverse/ && mirage configure -t spt && make depend
adding unit argument to 'start ()' (to delay execution)
mirage: [WARNING] Skipping version check, since our_version ("1.0.1-3592-g69baf09") fails to parse: only digits and . ...
Successfully pulled 27/27 repositories
The sources have been pulled to the duniverse folder. Run 'make build' to build the unikernel.
$ grep version duniverse/lwt/lwt.opam
opam-version: "2.0"
version: "6.1.1"
$ dune build
ocamlfind -toolchain solo5 ocamlopt    -c -o clock_stubs.o clock_stubs.c
ocamlfind -toolchain solo5 ocamlopt    -c -o mm_stubs.o mm_stubs.c
ocamlfind -toolchain solo5 ocamlopt    -c -o main.o main.c
ar r libmirage-solo5_bindings.a clock_stubs.o mm_stubs.o main.o
ar: creating libmirage-solo5_bindings.a
File "dune.build", line 11, characters 7-11:
11 |  (name main)
            ^^^^
Context: solo5
/usr/bin/ld: /home/user/.opam/5.3/lib/ocaml-solo5/lib/ocaml/libcamlruntime_eventsnat.a(runtime_events_consumer.n.o): in function `cursor_map_ring_file':
/home/user/.opam/5.3/.opam-switch/build/ocaml-solo5.1.1.0/ocaml/otherlibs/runtime_events/runtime_events_consumer.c:205:(.text.caml_runtime_events_create_cursor+0xb4): undefined reference to `fstat'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking (exit code 1)
```
I don't really have clues on how to fix that with Ocaml 5.x :(

**Comment by hannesm** [comment]
interesting, sorry it'll take me some time to look into this. just to be sure: this issue didn't appear with dune 3.21?

**Comment by hannesm** [comment]
so my current theory is that lwt>=6 (featuring runtime events) with ocaml > 5 will always require libruntimeevents, which is not available with mirage..

**Comment by hannesm** [comment]
please feel free to PR to opam-repository to revert my recent PR which allows lwt>=6 when dune 3.22 is there.

**Comment by palainp** [comment]
It was working before an "opam update && opam upgrade -y", and now I don't really know how to recompile with dune 3.21, it currently fails with:
```
File "duniverse/dune_/dune-project", line 1, characters 11-15:
1 | (lang dune 3.22)
               ^^^^
Error: Version 3.22 of the dune language is not supported.
Supported versions of this extension in version 3.22 of the dune language:
- 1.0 to 1.12
- 2.0 to 2.9
- 3.0 to 3.21
```
Indeed the dune_ folder in duniverse is at version 3.22 even with my local dune at version 3.21 as opam-monorepo really want to retrieve and use dune 3.22.

Sure I can propose a PR to revert the dune 3.22 + lwt 6 combo (is https://github.com/ocaml/opam-repository/commit/b97d5f1eec882a5f2039e714d02d05a3c71a2da7 the commit you meant?) but we will be stuck with lwt < 6 even with Ocaml 4.14. Lwt may be replaced with something else for Ocaml 5, but it may be sad for Ocaml 4?

**Comment by palainp** [comment]
Oups I was too slow for reverting :)

**Comment by hannesm** [comment]
@palainp it may be sad for OCaml 4... but that's life. maybe someone has the knowledge and time to look how this can be solved. as a first step, unbreaking the build on OCaml 5 is good -- better than having lwt 6 on OCaml 4, and nothing on OCaml 5. :)

**Comment by palainp** [comment]
Update on the "is there anything we can do", I just tried to add a fstat stub (the various types in struct stat are placeholder, and should be replace with something decent ;) ), and it compiles and works for tutorial/hello :
```C
#include <string.h>

typedef int dev_t;
typedef int ino_t;
typedef int mode_t;
typedef int nlink_t;
typedef int uid_t;
typedef int gid_t;
typedef int off_t;
typedef int blksize_t;
typedef int blkcnt_t;
typedef int time_t;

struct stat {
    dev_t     st_dev;
    ino_t     st_ino;
    mode_t    st_mode;
    nlink_t   st_nlink;
    uid_t     st_uid;
    gid_t     st_gid;
    dev_t     st_rdev;
    off_t     st_size;
    blksize_t st_blksize;
    blkcnt_t  st_blocks;
    time_t    st_atime;
    time_t    st_mtime;
    time_t    st_ctime;
};

int fstat(int fd, struct stat *statbuf)
{
    memset(statbuf, 0, sizeof(struct stat));
    return 0;  
}
```

fstat is used at https://github.com/ocaml/ocaml/blob/c40b6876b2d92cc3b07c73fed1669a3d485e7bb5/otherlibs/runtime_events/runtime_events_consumer.c#L201 and setting the st_size field lead to a 0B mmap (which succeed), and checks should be done later on the size before usage (I didn't checked right now, it was just for testing).

So to me, if ~~solo5~~ (EDIT: ocaml-solo5) onboard a fstat function it may be enough work to support libruntimeevent. I tried with another, more complex, unikernel and the xen target, and it worked too.

**Comment by palainp** [comment]
The struct stat content was taken from http://manpagesfr.free.fr/man/man2/stat.2.html, I don't have in my man 2 stat, and I didn't checked if that is portable or restricted to linux machines :(

**Comment by hannesm** [comment]
with ocaml-solo5 1.2.2 this is fine to merge. we can as well try to figure out a more complex (and correct!) constraint -- but is it worth it?

so, with ocaml-solo5 < 1.2.2 we need lwt < 6... but ocaml-solo5 is no direct mirage dependency... and also this is only an issue with ocaml > 5...

**Comment by palainp** [comment]
For now, I don't think it's worth looking for a more complex constraint. The main drawback is for OCaml 4 users who need features from LWT 6+; if such a user comes along, we'll probably find another constraint at that point :)

**Comment by hannesm** [comment]
@palainp maybe we misunderstand, my proposal is to merge this PR, and people with ocaml-solo5 before 1.2.2 on OCaml5 will have a tough time -- but I don't see why such systems should be around...

This means with modern opam-repository (and dune 3.22), everyone gets lwt6, and that works nicely.

**Comment by palainp** [comment]
> @palainp maybe we misunderstand, my proposal is to merge this PR, and people with ocaml-solo5 before 1.2.2 on OCaml5 will have a tough time -- but I don't see why such systems should be around...
> 
> This means with modern opam-repository (and dune 3.22), everyone gets lwt6, and that works nicely.

Oh yes, Ocaml4 was fine with it, so yes, it's fine to merge for me too! I don't either see if anyone need to restrict Ocaml5 and ocaml-solo5 before 1.2.2 :)
