### ISSUE TITLE
Kernel Build Problem for aarch64/arm

### ISSUE THREAD

**Issue by KenDickey** [mirage/mirage#919]
Greetings,

I am a noob, following the steps in

  https://mirage.io/wiki/arm64

Details attached.

Thanks for any help,
-KenD

[kernel-build-problem.txt](https://github.com/mirage/mirage/files/2341731/kernel-build-problem.txt)

**Comment by hannesm** [comment]
maybe @derpeter or @mato have some hints?

**Comment by KenDickey** [comment]
More info (retry Linux w KVM build)

[build-problm.txt](https://github.com/mirage/mirage/files/2364619/build-problm.txt)

**Comment by derpeter** [comment]
@KenDickey I never seen this errors but as you also used the 4.16 kernel there should be no difference on the source code side. Therefore i assume the problem is you toolchain. I did my builds with ubuntu 17.10 or 18.04 (not sure what it was at that time) And yours seems to be an 16.04.1. I would suggest you try a 18.04 VM or try to get a newer toolchain.

**Comment by KenDickey** [comment]
aarch64-linux-gnu-gcc (15:4.9.3+svn231177-1)  4.9.3 20150529 (prerelease)

Hmmm.. if 2015 above is the date, how is it that "apt-get update && apt-get upgrade" fails to update?

How do I fix this?

Thanks!
-KenD

**Comment by KenDickey** [comment]
PS: What swap of ocaml should I use?  (4.0{4,5,7}) ??

**Comment by derpeter** [comment]
@KenDickey apt-get updates you packages only "inside" of your distribution release. If gcc 4.9.* was shipped with your release of ubuntu it will only receive updates that are minor updates and / or security updates. If you want to get a current package you either need to upgrade to a newer release of your distribution or find a so called PPA which is a repository provided by a third party with newer packages or build the toolchain your self from source. 

If you don't want to upgrade your system the safest way will be to download an ubuntu 18.04 VM und do the compiling in the VM.

You should use the latest ocaml release and the latest opam release if possible. This should both be handelt by opam.

**Comment by KenDickey** [comment]
OK.  Installed Linux Mint 19.

Proximate error is now:

scripts/extract-cert.c:21:10: fatal error: openssl/bio.h: No such file or directory
 #include <openssl/bio.h>
          ^~~~~~~~~~~~~~~

vvv--- More Info ---vvv

kend@Content:~/MirageOS/Linux$ uname -a

Linux Content 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

kend@Content:~/MirageOS/Linux$ aarch64-linux-gnu-gcc --version
aarch64-linux-gnu-gcc (Ubuntu/Linaro 7.3.0-16ubuntu3) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

kend@Content:~/MirageOS/Linux$ ocaml -version
The OCaml toplevel, version 4.05.0

kend@Content:~/MirageOS/Linux$ opam --version
1.2.2

[build-prblm.txt](https://github.com/mirage/mirage/files/2372006/build-prblm.txt)

**Comment by mato** [comment]
You need the correct build dependencies installed to be able to build a kernel from source. In this case you want `apt-get install libssl-dev` or similar. If that is not enough, `apt-get build-dep linux` may help, or it may not (due to cross-compilation issues).

Sorry, but this is not a straightforward newbie operation :-). You may be better off trying to find a 64-bit distro you can straightforwardly install on your RPi (I presume you're using an RPi 3 or newer), however I'm not sure if one with a recent enough kernel and KVM enabled exists.

**Comment by derpeter** [comment]
@mato i haven't found such a distribution. If there is one i'm happy to update the tutorial.
Lets talk in 2 weaks about providing SD card images.

**Comment by KenDickey** [comment]
Thanks much.   Painful to put up with noobs.  I much appreciate your time.

I was able to build a kernel, but seem to have botched the setup files.  No display and I have to replace my broken usb-tty cable, so no diagnostics.

If you can post a SD card image for the RPi3 (or  aml-s905x-cc = LePotato) I would much apreciate it.

**Comment by mato** [comment]
The kernels based on our HOWTOs are all headless, i.e. you need the USB<->TTL cable for the console. Too painful to deal with the binary blobs etc required for graphics to work.

**Comment by KenDickey** [comment]
Ah!  I had assumed Linux KVM supplied framebuffer and USB drivers for keyboard/mouse.

Note Ultibo.org does this on raw RPi 3 hardware in Object Pasca, including graphics accelerationl.

The ARM "secret sauce" GUI blobs are a *real* pain!

Not my area of expertise, unfortunately. 

Thanks again for the help and info!

**Comment by KenDickey** [comment]
Got a tty<->usb connector. Works with Raspian.

Now I seem to have a problem with qemu-debootstrap setup:
--------------------------
Linux:x86-64:/mnt/mirage >>> sudo qemu-debootstrap --verbose --arch arm64 stretch /tmp/test
I: Running command: debootstrap --arch arm64 --foreign --verbose stretch /tmp/test
I: Keyring file not available at /usr/share/keyrings/debian-archive-keyring.gpg; switching to https mirror https://deb.debian.org/debian
I: Retrieving InRelease 
I: Retrieving Release 
...
...
I: Extracting liblzma5...
I: Extracting zlib1g...
I: Running command: chroot /tmp/test /debootstrap/debootstrap --second-stage
chroot: failed to run command ‘/debootstrap/debootstrap’: Exec format error
-------------------------------
Any ideas?  Thkx!

**Comment by derpeter** [comment]
have a look at https://github.com/RPi-Distro/pi-gen/issues/133 maybe you run into the same issue

**Comment by KenDickey** [comment]
FYI:

>> sudo modprobe binfmt_misc

did NOT fix the problem for me.

I will await a SD image.

Thanks again for the help and your time looking at this.

**Comment by mato** [comment]
You're welcome. Closing this in the mean time as it's not a bug on our end. (You can still comment here to get our attention, or use the mailing lists.)

**Comment by KenDickey** [comment]
ANOTHER WAY -- which works (at least on RasPi 3)

I took a break and installed aarch64 ArchLinuxArm on a SD for my Raspberry Pi 3 and noticed that kvm was used to bring up the kernel.

A light went on and I did the hello tutorial (output below).  I needed some additional packages.

OK. So after installing ArchLinuxArm
vvv---vvv
pacman -Syu opam ocaml
opam init
## 'opam mirage' fails at this point, but OK after:
pacman -Syu libvirt llvm-ocaml ocaml-compiler-libs  ocaml-ctypes  ocaml-findlib  ocaml-integers  ocaml-result  ocaml-topkg
opam install mirage
## optional:
opam install tuareg merlin ocaml-model 
^^^---^^^
Next I went through the 'hello' tutorial, and ...
vvv-------------------------vvv---------------------vvv
RasPi3:ArchLinux: ~/MirageOS/mirage-skeleton/tutorial/hello >>> ./ukvm-bin hello.ukvm
            |      ___|
  __|  _ \  |  _ \ __ \
\__ \ (   | | (   |  ) |
____/\___/ _|\___/____/
Solo5: Memory map: 512 MB addressable:
Solo5:     unused @ (0x0 - 0xfffff)
Solo5:       text @ (0x100000 - 0x20dfff)
Solo5:     rodata @ (0x20e000 - 0x23efff)
Solo5:       data @ (0x23f000 - 0x30bfff)
Solo5:       heap >= 0x30c000 < stack < 0x20000000
2018-09-15 23:33:07 -00:00: INF [application] hello
2018-09-15 23:33:08 -00:00: INF [application] hello
2018-09-15 23:33:09 -00:00: INF [application] hello
2018-09-15 23:33:10 -00:00: INF [application] hello
Solo5: solo5_exit(0) called
RasPi3:ArchLinux: ~/MirageOS/mirage-skeleton/tutorial/hello >>>

**Comment by Weichen81** [comment]
@mato @hannesm “-mgeneral-regs-only” is the AArch64 specified flag that is supported from GCC-4.8. Should we add a note for the minimal GCC version requirement for Arm64 in https://mirage.io/wiki/arm64 ?

Regards,
Wei Chen

**Comment by derpeter** [comment]
We should do that, Also maybe mention that if you are willing to go down the arch road you can cut some corners and start right away. From a "we want people to be able to run mirage on an pi" point of view this maybe a good idea.
