### ISSUE TITLE
error while configuring mirage-www

### ISSUE THREAD

**Issue by ZirakZaheer** [mirage/mirage#604]
ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
+ ocamlfind ocamlc -c -annot -bin-annot -package mirage -o config.cmo config.ml
File "config.ml", line 80, characters 44-48:
Error: The function applied to this argument has type
         ?group:string ->
         ?dhcp_key:bool Mirage.value ->
         ?net_key:[ `Direct | `Socket ] Mirage.value ->
         Mirage.stackv4 Functoria.impl
This argument cannot be applied without label
Command exited with code 2.
Hint: Recursive traversal of subdirectories was not enabled for this build,
  as the working directory does not look like an ocamlbuild project (no
  '_tags' or 'myocamlbuild.ml' file). If you have modules in subdirectories,
  you should add the option "-r" or create an empty '_tags' file.
  
  To enable recursive traversal for some subdirectories only, you can use the
  following '_tags' file:
  
      true: -traverse
      <dir1> or <dir2>: traverse

i am using mirage 2.9.0 I have also tried with 2.7.0 version.

**Comment by ZirakZaheer** [comment]
mirage configure ----> WORKED with 2.7.3

Now while running the make command I am getting the following error

File "dispatch.mli", line 25, characters 12-20:
Error: Unbound module type V1.CLOCK
Hint: Did you mean PCLOCK, MCLOCK or BLOCK?
Command exited with code 2.

Can someone tell what is the possible reason?

**Comment by mor1** [comment]
There are some recent interface updates that changed out `CLOCK` to `PCLOCK` and `MCLOCK`. In this particular case I guess it could be some inter-dependency between the package dependencies output from the `mirage` tool the OPAM dependency chain that causes packages to be installed (if the code output from `mirage configure` depends on `CLOCK` but the OPAM packages have been updated to provide `MCLOCK`/`PCLOCK` without adding appropriate version constraints). /cc @hannesm @yomimono @Drup ?

FWIW it's on my list to spend some time updating `mirage-www` this week (particularly removing the `camlp4` syntax dependency). Hopefully will have something done by the end of the week.

**Comment by yomimono** [comment]
@ZirakZaheer , are you attempting to build the `mirage-dev` branch of `mirage-www` by chance?  This branch is compatible with the trunk versions of many packages (including `mirage` and `mirage-types`) but not with the `2.x` versions currently available in the main `opam` repository.  To build with the currently released tools, you'll want to make sure you're building the `master` branch.

**Comment by ZirakZaheer** [comment]
@yomimono I did build the master branch indeed. I also tried to build the 'console example' available at mirage-skeleton repo. It was giving me an error (mentioned below) while running the make command:
'Unbounded Value Time' ----> ( line 6 see the code below) 

The code inside unikernel.ml is:

open Lwt.Infix

module Main (C: V1_LWT.CONSOLE) (Time: V1_LWT.TIME) = struct

  let start c _time =
    let rec loop = function
      | 0 -> Lwt.return_unit
      | n ->
        C.log_s c "hello" >>= fun () ->
        Time.sleep 1.0 >>= fun () ->
        C.log_s c "world" >>= fun () ->
        loop (n-1)
    in
    loop 4

end

This code I believe is correct. 

i am using Opam 1.2.2, ocamlfind 1.6.2, mirage 2.7.3

i also tried making the static_website app in the same repo but I was again getting some syntax or unbounded variable errors.

Is it due to some compiler mismatch or what? I have tried to reinstall everything multiple times and tried multiple versions of mirage.

**Comment by hannesm** [comment]
Dear @ZirakZaheer, the mirage-skeleton examples in the master branch are supposed to run with the most recent Mirage release, which is 2.9.1 at the moment.  Could you try mirage-2.9.1?

I don't know what the current state of mirage-www is (due to release preparations it might be broken atm)

**Comment by ZirakZaheer** [comment]
I am trying to install mirage-2.9.1 but its giving compile error.

Can you please tell which ocaml compiler to use for mirage-2.9.1?

Currently I am using 4.02.3

**Comment by hannesm** [comment]
I have it working with both 4.02.3 and 4.03.0.  What is the compilation error you get while compiling mirage-2.9.1?

**Comment by ZirakZaheer** [comment]
@hannesm
# E: Failure("Command ''/home/zirak/.opam/4.03.0/bin/ocamlbuild' lib_runtime/mirage-runtime.cma lib_runtime/mirage-runtime.cmxa lib_runtime/mirage-runtime.a lib_runtime/mirage-runtime.cmxs lib/mirage.cma lib/mirage.cmxa lib/mirage.a lib/mirage.cmxs lib/main.native -tag debug -classic-display' terminated with error code 10")
# make: *** [build] Error 1

**Comment by hannesm** [comment]
the actual error is missing -- could you compile it by hand to get a complete error (and paste this here)?

```
wget https://github.com/mirage/mirage/archive/v2.9.1.tar.gz
tar xf v2.9.1.tar.gz
cd mirage-2.9.1
make
```

**Comment by ZirakZaheer** [comment]
@hannesm 

zirak@zirak-VirtualBox:~/mirage-2.9.1$ make
ocamlopt.opt -o setup.bin setup.ml || ocamlopt -o setup.bin setup.ml || ocamlc -o setup.bin setup.ml
rm -f setup.cmx setup.cmi setup.o setup.cmo
./setup.bin -configure  --prefix /usr/local

Configuration: 
ocamlfind: ........................................... /home/zirak/.opam/4.03.0/bin/ocamlfind
ocamlc: .............................................. /home/zirak/.opam/4.03.0/bin/ocamlc.opt
ocamlopt: ............................................ /home/zirak/.opam/4.03.0/bin/ocamlopt.opt
ocamlbuild: .......................................... /home/zirak/.opam/4.03.0/bin/ocamlbuild
Package name: ........................................ mirage
Package version: ..................................... 2.9.1
os_type: ............................................. Unix
system: .............................................. linux
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.03.0
standard_library_default: ............................ /home/zirak/.opam/4.03.0/lib/ocaml
standard_library: .................................... /home/zirak/.opam/4.03.0/lib/ocaml
standard_runtime: .................................... /home/zirak/.opam/4.03.0/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC
native_c_compiler: ................................... gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.6.2
is_native: ........................................... true
suffix_program: ...................................... 
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: ......................... 
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_functoria_runtime: ............................... /home/zirak/.opam/4.03.0/lib/functoria
pkg_ipaddr: .......................................... /home/zirak/.opam/4.03.0/lib/ipaddr
pkg_astring: ......................................... /home/zirak/.opam/4.03.0/lib/astring
pkg_logs: ............................................ /home/zirak/.opam/4.03.0/lib/logs
pkg_functoria: ....................................... /home/zirak/.opam/4.03.0/lib/functoria
pkg_functoria_app: ................................... /home/zirak/.opam/4.03.0/lib/functoria
ocamldoc: ............................................ /home/zirak/.opam/4.03.0/bin/ocamldoc

echo "let current = \"2.9.1\"" > lib/mirage_version.ml
./setup.bin -build -classic-display
/home/zirak/.opam/4.03.0/bin/ocamlopt.opt unix.cmxa -I /home/zirak/.opam/4.03.0/lib/ocamlbuild /home/zirak/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa myocamlbuild.ml /home/zirak/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_runtime.mli > lib_runtime/mirage_runtime.mli.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmi lib_runtime/mirage_runtime.mli
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_runtime.ml > lib_runtime/mirage_runtime.ml.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_info.mli > lib_runtime/mirage_info.mli.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmi lib_runtime/mirage_info.mli
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria.runtime -package ipaddr -package logs -modules lib_runtime/mirage_info.ml > lib_runtime/mirage_info.ml.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmo lib_runtime/mirage_runtime.ml
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmo lib_runtime/mirage_info.ml
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -a -dontlink unix lib_runtime/mirage_runtime.cmo lib_runtime/mirage_info.cmo -o lib_runtime/mirage-runtime.cma
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_runtime.cmx lib_runtime/mirage_runtime.ml
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -package astring -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib_runtime -o lib_runtime/mirage_info.cmx lib_runtime/mirage_info.ml
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlopt -a -dontlink unix lib_runtime/mirage_runtime.cmx lib_runtime/mirage_info.cmx -o lib_runtime/mirage-runtime.cmxa
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlopt -shared -dontlink unix lib_runtime/mirage-runtime.cmxa lib_runtime/mirage_runtime.cmx lib_runtime/mirage_info.cmx -o lib_runtime/mirage-runtime.cmxs
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage.mli > lib/mirage.mli.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage_key.mli > lib/mirage_key.mli.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage_key.cmi lib/mirage_key.mli
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmi lib/mirage.mli
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage.ml > lib/mirage.ml.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage_version.ml > lib/mirage_version.ml.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage_version.cmo lib/mirage_version.ml
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamldep -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -modules lib/mirage_key.ml > lib/mirage_key.ml.depends
/home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmo lib/mirage.ml
+ /home/zirak/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -safe-string -short-paths -principal -keep-locs -strict-sequence -I lib_runtime -I lib -package astring -package functoria -package functoria.app -package functoria.runtime -package ipaddr -package logs -w +A-4-6-7-9-40-42-44-48 -I lib -I lib_runtime -o lib/mirage.cmo lib/mirage.ml
File "lib/mirage.ml", line 1565, characters 28-44:
Error: Unbound value get_base_context
Command exited with code 2.
E: Failure("Command ''/home/zirak/.opam/4.03.0/bin/ocamlbuild' lib_runtime/mirage-runtime.cma lib_runtime/mirage-runtime.cmxa lib_runtime/mirage-runtime.a lib_runtime/mirage-runtime.cmxs lib/mirage.cma lib/mirage.cmxa lib/mirage.a lib/mirage.cmxs lib/main.native -tag debug -classic-display' terminated with error code 10")
make: *** [build] Error 1

**Comment by hannesm** [comment]
ok, which version of functoria do you have installed? (`opam info functoria | grep installed`)

**Comment by ZirakZaheer** [comment]
1.1.1

**Comment by hannesm** [comment]
hmm, but that release has a `get_base_context` defined [here](https://github.com/mirage/functoria/blob/1.1.1/app/functoria_app.mli#L110).  Are you sure that this functoria is installed and used?  Could you do a `opam reinstall functoria` followed by `make clean && make` in mirage?

**Comment by ZirakZaheer** [comment]
@hannesm 
Okay so it turned out I had two conflicting versions of opam installed one via apt-get and the other one built from source,
somehow the packages installed were conflicting whenever I ran the configure command.

So, I deleted both made a fresh opam install and now everything seems to be working.

I am trying to build static-website

mirage configure -t xen --dhcp=true     (--dhcp part is not fitting well in this command any idea how can I enable dhcp in someother way)

Thanks alot

**Comment by hannesm** [comment]
you're welcome.  the `dhcp true` argument should work fine (does it?). since this issue is solved, could you please open a new issue if you encounter further problems with mirage-skeleton!?
